import {
  ScrollView,
  View,
  Text,
  Image,
  Pressable,
  StyleSheet,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Haptics from "expo-haptics";
import { colors, typography, spacing } from "@/lib/theme";
import { useReview } from "@/lib/hooks/use-reviews";
import { ScoreDisplay } from "@/components/ScoreDisplay";
import { SectionBlock } from "@/components/SectionBlock";
import { PairingCard } from "@/components/PairingCard";
import { Divider } from "@/components/Divider";
import { supabase } from "@/lib/supabase";

const SECTION_ORDER = [
  { key: "first_impression", label: "First Impression" },
  { key: "fit_for_you", label: "Fit For You" },
  { key: "style_read", label: "Style Read" },
  { key: "originality", label: "Originality" },
  { key: "construction", label: "Construction" },
  { key: "color_story", label: "Color Story" },
  { key: "occasion_fit", label: "Occasion Fit" },
  { key: "pairing", label: "Pairing" },
  { key: "alternatives", label: "Alternatives" },
  { key: "critique", label: "Critique" },
  { key: "final_word", label: "Final Word" },
] as const;

export default function ReviewScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { data: review, isLoading } = useReview(id);

  if (isLoading || !review) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <Text style={styles.loadingText}>Loading...</Text>
        </View>
      </SafeAreaView>
    );
  }

  const imageUrl = review.photo_storage_path
    ? supabase.storage
        .from("scan-uploads")
        .getPublicUrl(review.photo_storage_path).data.publicUrl
    : null;

  const sections = review.sections as Record<string, string>;

  const handleSaveToWardrobe = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    await supabase.from("wardrobe_items").insert({
      item_name: review.item_name ?? "Unknown item",
      category: "other",
      color_tags: [],
      original_review_id: review.id,
    });
  };

  const pairingItems = sections.pairing
    ? sections.pairing.split("\n").filter((line: string) => line.trim())
    : [];

  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <View style={styles.topBar}>
        <Pressable onPress={() => router.back()}>
          <Text style={styles.backText}>← Back</Text>
        </Pressable>
      </View>

      <ScrollView showsVerticalScrollIndicator={false}>
        {imageUrl && (
          <Image source={{ uri: imageUrl }} style={styles.heroImage} />
        )}

        <ScoreDisplay score={review.score} />

        <View style={styles.itemInfo}>
          <Text style={styles.itemName}>
            {review.item_name ?? "Unknown Item"}
          </Text>
          <Text style={styles.itemMeta}>
            {review.brand_guess ?? "Unknown brand"}
          </Text>
        </View>

        <Divider />

        {SECTION_ORDER.map(({ key, label }) => {
          const content = sections[key];
          if (!content) return null;

          if (key === "pairing") {
            return (
              <View key={key} style={styles.pairingSection}>
                <Text style={styles.pairingSectionHeader}>{label}</Text>
                <ScrollView
                  horizontal
                  showsHorizontalScrollIndicator={false}
                  contentContainerStyle={styles.pairingScroll}
                >
                  {pairingItems.map((item, i) => (
                    <PairingCard
                      key={i}
                      title={item.replace(/^[-—•]\s*/, "")}
                    />
                  ))}
                </ScrollView>
              </View>
            );
          }

          return (
            <SectionBlock
              key={key}
              header={label}
              body={content}
              isFinalWord={key === "final_word"}
              priceEstimate={
                key === "construction" ? review.price_estimate : null
              }
            />
          );
        })}

        <View style={styles.footer}>
          <Text style={styles.aiDisclosure}>
            Generated by AI — opinions are Juno's, not yours.
          </Text>
        </View>
      </ScrollView>

      <View style={styles.bottomBar}>
        <Pressable onPress={() => router.push("/(tabs)/scan")}>
          <Text style={styles.bottomBtnPrimary}>Scan Again</Text>
        </Pressable>
        <Pressable onPress={handleSaveToWardrobe}>
          <Text style={styles.bottomBtn}>Save to Wardrobe</Text>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    ...typography.body,
    color: colors.textMuted,
  },
  topBar: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  backText: {
    fontFamily: "Inter_300Light",
    fontSize: 14,
    color: "#777777",
  },
  heroImage: {
    width: "100%",
    height: 300,
    resizeMode: "cover",
  },
  itemInfo: {
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  itemName: {
    ...typography.headline,
    marginBottom: 6,
  },
  itemMeta: {
    ...typography.meta,
  },
  pairingSection: {
    paddingVertical: spacing.sectionPadding,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  pairingSectionHeader: {
    ...typography.sectionHeader,
    paddingHorizontal: spacing.horizontalPadding,
    marginBottom: 14,
  },
  pairingScroll: {
    paddingHorizontal: spacing.horizontalPadding,
    gap: 12,
  },
  footer: {
    paddingVertical: 20,
    paddingHorizontal: spacing.horizontalPadding,
    alignItems: "center",
  },
  aiDisclosure: {
    ...typography.caption,
  },
  bottomBar: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 32,
    paddingVertical: 16,
    paddingHorizontal: spacing.horizontalPadding,
    backgroundColor: "rgba(17,17,17,0.95)",
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  bottomBtn: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: "#777777",
    paddingVertical: 6,
  },
  bottomBtnPrimary: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: colors.textPrimary,
    paddingVertical: 6,
  },
});
